### ISSUE TITLE
feature request - macOS support with pbcopy and  pbpaste clipboard

### ISSUE THREAD

**Issue by kiil** [zsh-vi-more/evil-registers#11]
Would be great if this could be used as is in macos terminal, so:

feature request - macos support with pbcopy and  pbpaste clipboard

**Comment by xPMo** [comment]
I'm not familiar with Mac myself. Does pbcopy/pbpaste have multiple selection buffers (like Linux with primary and clipboard), or just the one?

**Comment by xPMo** [comment]
Check out `dev` for an implementation, let me know if that works. (Since I can't test it myself.)

**Comment by kiil** [comment]
It works :) Thanks a lot!

> Does pbcopy/pbpaste have multiple selection buffers (like Linux with primary and clipboard), or just the one?

Just one.
