### ISSUE TITLE
Yank to alphabetic registers is recognized only on the spot.

### ISSUE THREAD

**Issue by wikbon** [zsh-vi-more/evil-registers#15]
Good time of the day to you! You've done a great job with the plugin, thank you very much! A problem i'm having is that after installing remote nvim(which had me enabling break-system-packages and using --user flag to install it to /.local/bin, and adding that to the path for zsh) yanking to alphabetic register works, and i can paste it back to the zsh session i've copied it from(so yank a line to "u and paste it back from "u on the spot). But when i try to paste it into neovim(no matter if i run it in a different session or in the same one after yanking) it says that there is nothing in "u register. 
I would appreciate any help troubleshooting it, as usually i would poke around myself, but with zsh, remotenvim and nvim interaction i'm completely lost at where to even begin looking.

Edit: if i close nvim which was launched from the session i yanked text from i can still paste it back to zsh.

**Comment by xPMo** [comment]
> enabling break-system-packages

Hopefully neovim-remote won't be necessary in the future (NVIM >=0.9 has `--remote` capabilities, but some that this plugin would rely on are [half-broken currently](/neovim/neovim/issues/22970)).

I'll take a closer look tomorrow and try to reproduce, but here's a couple things that would help:

- Does yanking in Neovim and then pasting in Zsh work?
- With a neovim session running, do you see any output to `print -rl {$XDG_RUNTIME_DIR,/tmp}/nvim*(N=)`?

**Comment by xPMo** [comment]
Okay, got back to my PC and did some testing. It *seems* that `--remote-expr` is working as intended. I'm going to ask in the issue to confirm.

If you're on Neovim v0.10, check out the `dev` branch. It removes the `nvr` requirement and just relies on nvim.

If it works for you, then I think I'll merge #14.

**Comment by wikbon** [comment]
>     * Does yanking in Neovim and then pasting in Zsh work?
 - nope
>     * With a neovim session running, do you see any output to `print -rl {$XDG_RUNTIME_DIR,/tmp}/nvim*(N=)`?
$ print -rl {$XDG_RUNTIME_DIR,/tmp}/nvim*(N=)
/run/user/1000/nvim.10882.0
 i'll be checking the dev branch a bit latter a come back with how it goes, thank you!

**Comment by wikbon** [comment]
after switching to the dev everything works fine! the only strange thing i've encountered so far was fun interaction when i had something yanked from nvim to "u for the small test above. After installing dev and re-starting the zsh session, I've yanked from zsh to "u  to paste it into nvim a got  my old "u yanked from nvim + "u yanked from zsh appended at the end. Was unable to replicate, seems like some small hiccup. Appreciate the help, and the work on the plugin, great stuff!

**Comment by xPMo** [comment]
Alright, `dev` is merged into `master`, so you can switch back to that if you wish, or check out the `4.0` tag. (I figure a full year is long enough for most Neovim+Zsh users to switch to >=0.9.)
